# Default initial positions for R1SN003's ros2_control system

initial_positions:
  l_elbow_joint: 0
  l_hand_paddle_distal_joint: 0
  l_hand_paddle_proximal_joint: 0
  l_hand_thumb_distal_joint: 0
  l_hand_thumb_proximal_joint: 0
  l_shoulder_pitch_joint: 0
  l_shoulder_roll_joint: 0
  l_shoulder_yaw_joint: 0
  l_wrist_heave_eq_joint: 0
  l_wrist_pitch_eq_joint: 0
  l_wrist_pronosupination_joint: 0
  l_wrist_roll_eq_joint: 0
  r_elbow_joint: 0
  r_hand_paddle_distal_joint: 0
  r_hand_paddle_proximal_joint: 0
  r_hand_thumb_distal_joint: 0
  r_hand_thumb_proximal_joint: 0
  r_shoulder_pitch_joint: 0
  r_shoulder_roll_joint: 0
  r_shoulder_yaw_joint: 0
  r_wrist_heave_eq_joint: 0
  r_wrist_pitch_eq_joint: 0
  r_wrist_pronosupination_joint: 0
  r_wrist_roll_eq_joint: 0