# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - l_shoulder_pitch_joint
      - l_shoulder_roll_joint
      - l_shoulder_yaw_joint
      - l_elbow_joint
      - l_wrist_pronosupination_joint
      - l_wrist_heave_eq_joint
      - l_wrist_roll_eq_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity